import { jsPDF } from "jspdf";
import { autoTable } from "jspdf-autotable";

/*
 * =========================================================
 * INVOICE PDF GENERATOR
 * =========================================================
 *
 * This file is shared by both the photographer and client
 * invoice pages so that both users download the same
 * professionally formatted invoice.
 *
 * Required packages:
 *
 * npm install jspdf jspdf-autotable
 *
 * =========================================================
 */


/*
 * Format a number as New Zealand currency.
 */
function money(value) {
    return new Intl.NumberFormat("en-NZ", {
        style: "currency",
        currency: "NZD",
        minimumFractionDigits: 2,
    }).format(Number(value) || 0);
}


/*
 * Format a database date using the NZ date format.
 */
function date(value) {
    if (!value) return "—";

    return new Date(
        `${value}T00:00:00`
    ).toLocaleDateString("en-NZ", {
        day: "2-digit",
        month: "long",
        year: "numeric",
    });
}


/*
 * Format a database time value.
 */
function time(value) {
    if (!value) return "";

    return new Date(
        `1970-01-01T${value}`
    ).toLocaleTimeString("en-NZ", {
        hour: "numeric",
        minute: "2-digit",
    });
}


/*
 * Build the client's display name.
 */
function clientName(profile) {
    const fullName = [
        profile?.first_name,
        profile?.last_name,
    ]
        .filter(Boolean)
        .join(" ")
        .trim();

    return (
        fullName ||
        profile?.email ||
        "Client"
    );
}


/*
 * Remove characters that should not appear in a
 * downloaded filename.
 */
function cleanFileName(value) {
    return String(value || "invoice")
        .replace(
            /[<>:"/\\|?*\u0000-\u001F]/g,
            "-"
        )
        .replace(/\s+/g, "-")
        .replace(/-+/g, "-")
        .replace(/^-|-$/g, "");
}


/*
 * Add wrapped text to the PDF and return the next
 * available Y position.
 */
function addWrappedText(
    doc,
    text,
    x,
    y,
    maxWidth,
    options = {}
) {
    if (!text) return y;

    const lines = doc.splitTextToSize(
        String(text),
        maxWidth
    );

    doc.text(
        lines,
        x,
        y,
        options
    );

    return y + lines.length * 5;
}


/*
 * Add the LensFlow footer to every page.
 */
function addPageFooter(
    doc,
    invoiceNumber
) {
    const pages = doc.getNumberOfPages();

    for (
        let page = 1;
        page <= pages;
        page += 1
    ) {
        doc.setPage(page);

        doc.setDrawColor(
            225,
            225,
            230
        );

        doc.line(
            18,
            282,
            192,
            282
        );

        doc.setFont(
            "helvetica",
            "normal"
        );

        doc.setFontSize(8);

        doc.setTextColor(
            125,
            125,
            135
        );

        doc.text(
            `${invoiceNumber} • Generated by LensFlow`,
            18,
            288
        );

        doc.text(
            `Page ${page} of ${pages}`,
            192,
            288,
            {
                align: "right",
            }
        );
    }
}


/*
 * =========================================================
 * CREATE INVOICE PDF
 * =========================================================
 *
 * Creates and returns a jsPDF document.
 *
 * This function does not automatically download the file.
 * That allows the same PDF generator to later be reused
 * for invoice email attachments.
 */
export function createInvoicePdf({
    invoice,
    items = [],
    clientProfile = null,
    booking = null,
    service = null,
    photographerProfile = null,
}) {
    if (!invoice) {
        throw new Error(
            "Invoice data is required to generate a PDF."
        );
    }


    /*
     * Create an A4 portrait document.
     */
    const doc = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
    });


    /*
     * Invoice information.
     */
    const businessName =
        photographerProfile?.business_name ||
        "Photography Business";

    const billedTo =
        clientName(clientProfile);

    const status =
        invoice.displayStatus ||
        invoice.status ||
        "draft";

    const taxRate =
        Number(invoice.tax_rate) || 0;


    /*
     * PDF colour palette.
     *
     * These values give the invoice a subtle LensFlow-style
     * purple accent while keeping the actual document clean
     * and professional.
     */
    const accent = [
        91,
        74,
        126,
    ];

    const heading = [
        42,
        42,
        48,
    ];

    const body = [
        95,
        95,
        105,
    ];

    const muted = [
        130,
        130,
        140,
    ];

    const line = [
        225,
        225,
        230,
    ];

    const soft = [
        247,
        246,
        250,
    ];


    /*
     * =====================================================
     * TOP ACCENT
     * =====================================================
     */

    doc.setFillColor(...accent);

    doc.rect(
        0,
        0,
        210,
        5,
        "F"
    );


    /*
     * =====================================================
     * BUSINESS / INVOICE HEADER
     * =====================================================
     */

    doc.setFont(
        "helvetica",
        "bold"
    );

    doc.setFontSize(10);

    doc.setTextColor(...accent);

    doc.text(
        businessName.toUpperCase(),
        18,
        18
    );


    doc.setFontSize(26);

    doc.setTextColor(...heading);

    doc.text(
        "INVOICE",
        18,
        32
    );


    doc.setFont(
        "helvetica",
        "normal"
    );

    doc.setFontSize(11);

    doc.setTextColor(...body);

    doc.text(
        invoice.invoice_number ||
            "Invoice",
        18,
        40
    );


    /*
     * Invoice status.
     */
    doc.setFont(
        "helvetica",
        "bold"
    );

    doc.setFontSize(9);

    doc.setTextColor(...accent);

    doc.text(
        String(status).toUpperCase(),
        18,
        47
    );


    /*
     * =====================================================
     * INVOICE META INFORMATION
     * =====================================================
     */

    const metaX = 132;
    const metaValueX = 192;


    doc.setFontSize(8);

    doc.setTextColor(...muted);

    doc.text(
        "ISSUE DATE",
        metaX,
        20
    );

    doc.text(
        "DUE DATE",
        metaX,
        30
    );


    doc.setFont(
        "helvetica",
        "bold"
    );

    doc.setFontSize(9);

    doc.setTextColor(...heading);

    doc.text(
        date(invoice.issue_date),
        metaValueX,
        20,
        {
            align: "right",
        }
    );


    doc.text(
        invoice.due_date
            ? date(invoice.due_date)
            : "No due date",
        metaValueX,
        30,
        {
            align: "right",
        }
    );


    /*
     * GST / Tax number.
     */
    if (invoice.tax_number) {
        doc.setFont(
            "helvetica",
            "normal"
        );

        doc.setFontSize(8);

        doc.setTextColor(...muted);

        doc.text(
            "GST / TAX NUMBER",
            metaX,
            40
        );


        doc.setFont(
            "helvetica",
            "bold"
        );

        doc.setFontSize(9);

        doc.setTextColor(...heading);

        doc.text(
            String(invoice.tax_number),
            metaValueX,
            40,
            {
                align: "right",
            }
        );
    }


    /*
     * Header divider.
     */
    doc.setDrawColor(...line);

    doc.line(
        18,
        56,
        192,
        56
    );


    /*
     * =====================================================
     * CLIENT + BOOKING INFORMATION
     * =====================================================
     */

    doc.setFont(
        "helvetica",
        "bold"
    );

    doc.setFontSize(8);

    doc.setTextColor(...muted);

    doc.text(
        "BILLED TO",
        18,
        67
    );

    doc.text(
        "BOOKING",
        110,
        67
    );


    /*
     * Client name.
     */
    doc.setFontSize(11);

    doc.setTextColor(...heading);

    doc.text(
        billedTo,
        18,
        75
    );


    /*
     * Booking service.
     */
    const serviceName =
        service?.name ||
        booking?.services?.name ||
        "Photography Booking";


    doc.text(
        booking
            ? serviceName
            : "No booking information",
        110,
        75
    );


    /*
     * Client contact details.
     */
    doc.setFont(
        "helvetica",
        "normal"
    );

    doc.setFontSize(9);

    doc.setTextColor(...body);


    let leftY = 82;


    if (clientProfile?.email) {
        doc.text(
            clientProfile.email,
            18,
            leftY
        );

        leftY += 5;
    }


    if (clientProfile?.phone) {
        doc.text(
            clientProfile.phone,
            18,
            leftY
        );
    }


    /*
     * Booking information.
     */
    if (booking) {
        let rightY = 82;


        if (booking.booking_date) {
            doc.text(
                date(
                    booking.booking_date
                ),
                110,
                rightY
            );

            rightY += 5;
        }


        if (booking.start_time) {
            const timeText =
                booking.end_time
                    ? `${time(
                          booking.start_time
                      )} – ${time(
                          booking.end_time
                      )}`
                    : time(
                          booking.start_time
                      );


            doc.text(
                timeText,
                110,
                rightY
            );

            rightY += 5;
        }


        if (booking.location) {
            addWrappedText(
                doc,
                booking.location,
                110,
                rightY,
                82
            );
        }
    }


    /*
     * =====================================================
     * INVOICE ITEMS TABLE
     * =====================================================
     */

    autoTable(doc, {
        startY: 103,

        margin: {
            left: 18,
            right: 18,
            bottom: 24,
        },

        head: [
            [
                "Description",
                "Qty",
                "Unit Price",
                "Amount",
            ],
        ],

        body:
            items.length > 0
                ? items.map(
                      (item) => [
                          item.description ||
                              "Invoice item",

                          String(
                              Number(
                                  item.quantity
                              ) || 0
                          ),

                          money(
                              item.unit_price
                          ),

                          money(
                              item.subtotal
                          ),
                      ]
                  )
                : [
                      [
                          "No itemised charges available",
                          "",
                          "",
                          "",
                      ],
                  ],

        theme: "plain",

        styles: {
            font: "helvetica",
            fontSize: 9,
            textColor: body,

            cellPadding: {
                top: 4,
                right: 3,
                bottom: 4,
                left: 3,
            },

            lineColor: line,

            lineWidth: {
                bottom: 0.2,
            },
        },

        headStyles: {
            fillColor: soft,
            textColor: muted,
            fontStyle: "bold",
            fontSize: 8,
        },

        columnStyles: {
            0: {
                cellWidth: 82,
            },

            1: {
                cellWidth: 18,
                halign: "right",
            },

            2: {
                cellWidth: 34,
                halign: "right",
            },

            3: {
                cellWidth: 34,
                halign: "right",
            },
        },
    });


    /*
     * Continue below the table.
     */
    let y =
        (
            doc.lastAutoTable
                ?.finalY || 103
        ) + 10;


    /*
     * Helper used to prevent content from being written
     * beyond the printable page area.
     */
    const ensureSpace = (
        needed = 35
    ) => {
        if (y + needed > 270) {
            doc.addPage();
            y = 20;
        }
    };


    /*
     * =====================================================
     * TOTALS
     * =====================================================
     */

    ensureSpace(45);


    const totalsX = 132;
    const totalsValueX = 192;


    doc.setFont(
        "helvetica",
        "normal"
    );

    doc.setFontSize(9);

    doc.setTextColor(...body);


    /*
     * Subtotal.
     */
    doc.text(
        "Subtotal",
        totalsX,
        y
    );

    doc.text(
        money(invoice.subtotal),
        totalsValueX,
        y,
        {
            align: "right",
        }
    );


    /*
     * GST.
     */
    y += 7;


    doc.text(
        `GST (${taxRate.toFixed(
            2
        )}%)${
            invoice.tax_included
                ? " included"
                : ""
        }`,
        totalsX,
        y
    );


    doc.text(
        money(
            invoice.tax_amount
        ),
        totalsValueX,
        y,
        {
            align: "right",
        }
    );


    /*
     * Total divider.
     */
    y += 5;


    doc.setDrawColor(...line);

    doc.line(
        totalsX,
        y,
        totalsValueX,
        y
    );


    /*
     * Grand total.
     */
    y += 9;


    doc.setFont(
        "helvetica",
        "bold"
    );

    doc.setFontSize(12);

    doc.setTextColor(...heading);


    doc.text(
        "TOTAL (NZD)",
        totalsX,
        y
    );


    doc.setTextColor(...accent);


    doc.text(
        money(
            invoice.total_amount
        ),
        totalsValueX,
        y,
        {
            align: "right",
        }
    );


    /*
     * =====================================================
     * GST TREATMENT INFORMATION
     * =====================================================
     */

    y += 13;


    ensureSpace(38);


    doc.setFillColor(...soft);


    doc.roundedRect(
        18,
        y,
        92,
        28,
        2,
        2,
        "F"
    );


    doc.setFont(
        "helvetica",
        "bold"
    );

    doc.setFontSize(8);

    doc.setTextColor(...muted);


    doc.text(
        "GST TREATMENT",
        23,
        y + 7
    );


    doc.setFontSize(9);

    doc.setTextColor(...heading);


    doc.text(
        `${taxRate.toFixed(
            2
        )}% GST ${
            invoice.tax_included
                ? "included"
                : "added"
        }`,
        23,
        y + 14
    );


    doc.setFont(
        "helvetica",
        "normal"
    );

    doc.setFontSize(8);

    doc.setTextColor(...body);


    addWrappedText(
        doc,

        invoice.tax_included
            ? "Service prices already include GST. The GST component is shown separately."
            : "GST is calculated on top of the service prices.",

        23,
        y + 20,
        82
    );


    y += 38;


    /*
     * =====================================================
     * BANK TRANSFER DETAILS
     * =====================================================
     */

    if (
        invoice.bank_account_name &&
        invoice.bank_account_number
    ) {
        ensureSpace(45);


        doc.setDrawColor(...line);

        doc.line(
            18,
            y,
            192,
            y
        );


        y += 9;


        doc.setFont(
            "helvetica",
            "bold"
        );

        doc.setFontSize(9);

        doc.setTextColor(...heading);


        doc.text(
            "BANK TRANSFER DETAILS",
            18,
            y
        );


        y += 8;


        doc.setFont(
            "helvetica",
            "normal"
        );

        doc.setFontSize(9);

        doc.setTextColor(...body);


        /*
         * Account name.
         */
        doc.text(
            `Account Name: ${invoice.bank_account_name}`,
            18,
            y
        );


        y += 6;


        /*
         * Bank name.
         */
        if (invoice.bank_name) {
            doc.text(
                `Bank: ${invoice.bank_name}`,
                18,
                y
            );

            y += 6;
        }


        /*
         * Account number.
         */
        doc.text(
            `Account Number: ${invoice.bank_account_number}`,
            18,
            y
        );


        y += 7;


        /*
         * Additional payment instructions.
         */
        if (
            invoice.bank_payment_instructions
        ) {
            y = addWrappedText(
                doc,
                invoice.bank_payment_instructions,
                18,
                y,
                174
            );
        }


        y += 5;
    }


    /*
     * =====================================================
     * INVOICE NOTES
     * =====================================================
     */

    if (invoice.notes) {
        ensureSpace(30);


        doc.setDrawColor(...line);

        doc.line(
            18,
            y,
            192,
            y
        );


        y += 9;


        doc.setFont(
            "helvetica",
            "bold"
        );

        doc.setFontSize(9);

        doc.setTextColor(...heading);


        doc.text(
            "NOTES",
            18,
            y
        );


        y += 7;


        doc.setFont(
            "helvetica",
            "normal"
        );

        doc.setFontSize(9);

        doc.setTextColor(...body);


        y = addWrappedText(
            doc,
            invoice.notes,
            18,
            y,
            174
        );
    }


    /*
     * =====================================================
     * PAGE FOOTERS
     * =====================================================
     */

    addPageFooter(
        doc,
        invoice.invoice_number ||
            "Invoice"
    );


    /*
     * Return the completed jsPDF document.
     */
    return doc;
}


/*
 * =========================================================
 * DOWNLOAD PDF
 * =========================================================
 *
 * Used by both the photographer and client invoice pages.
 */
export function downloadInvoicePdf(
    data
) {
    const doc =
        createInvoicePdf(data);

    const invoiceNumber =
        data?.invoice
            ?.invoice_number ||
        "invoice";


    doc.save(
        `${cleanFileName(
            invoiceNumber
        )}.pdf`
    );
}


/*
 * =========================================================
 * GET PDF AS BLOB
 * =========================================================
 *
 * We are not using this yet, but it is intentionally
 * included for the next stage of LensFlow.
 *
 * When we implement invoice emailing, the same PDF
 * generator can produce a Blob rather than downloading
 * the document in the browser.
 */
export function getInvoicePdfBlob(
    data
) {
    const doc =
        createInvoicePdf(data);

    return doc.output("blob");
}